### PR TITLE
added bpm release to deployment.

### PR DESCRIPTION
**Pull request by mxplusb**
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>

### CODE REVIEW

**Comment by mxplusb** [comment]
@bengerman13

**Comment by jontours** [comment]
I'm gonna have to say this is probably not we want.  This will apply BPM across all deployments, which we really don't want.  I'd rather just add it using the https://github.com/18F/cg-deploy-opslogin repo.

**Comment by mxplusb** [comment]
Why shouldn't we apply it to all deployments?

**Comment by jontours** [comment]
It just seems to me like a heavy handed approach to fix one, small problem.  I'd like to minimize putting _anything_ in the runtime config until it's absolutely unavoidable.

**Comment by mxplusb** [comment]
Makes sense.

**Pull request closed without merging**
