### PR TITLE
Add jobs to bosh deployments:

### PR DESCRIPTION
**Pull request by sharms**
- hardening scripts from fisma
- tripwire agent
- nessus-agent
- newrelic monitoring
- riemann client
- clamav
- snort

### CODE REVIEW

**Comment by jmcarp** [comment]
So `bosh-deployment.yml` is used to deploy tooling-bosh, staging-bosh, and production-bosh, right? Does that mean that the master-bosh / bosh-init director needs all the hardening releases (fisma, tripwire, etc.)? Do we need to make sure tooling-bosh has the releases before it deploys staging-bosh and production-bosh?

**Comment by rogeruiz** [comment]
Have to remove `riemann` and `collectd` due to 18F/cg-atlas#116

**Comment by rogeruiz** [comment]
I've updated this PR by removing `riemann`. I've also uploaded the secrets for `prod-bosh` and `staging-bosh` to include the relevant bits to deploy the rest.

AFAIK, @LinuxBozo should be working / thinking about the related cards that came up around having these releases available for `master-bosh` and `tooling-bosh`.

please see 18F/cg-atlas#62 for more details.

**Comment by jmcarp** [comment]
@rogeruiz: it looks like we're still using `riemannc` in `templates`, even though it's deleted from `releases`. Also, jobs like `clamav` and `snort` need `riemannc`--without the riemann client, alerts aren't going to get sent, which means those services aren't going to do anything for the time being.

**Pull request merged**
