### PR TITLE
Mor Ram.

### PR DESCRIPTION
**Pull request by jontours**

### CODE REVIEW

**Comment by bengerman13** [comment]
Should we consider moving to t3.small or t3.medium instead?

**Comment by jontours** [comment]
Good call, t3.small should suffice.

**Comment by jontours** [comment]
@bengerman13 now that I think about it t2.medium would probably be best.

**Comment by jontours** [comment]
We are currently running low on ram for this vm, going to t3.small doesn't seem to guarantee fixing that problem.

**Comment by bengerman13** [comment]
t3.medium is (slightly) cheaper and has the same specs (but a newer CPU generation, so probably a little faster)

**Comment by jontours** [comment]
Done.  Thanks @bengerman13!

**Pull request merged**
